# general data for tool
hou_main_versions:
  - 18:
  - 18.5:
  - 19:
houdini_sub_versions:
houdini_paths:
  linux: /opt/hfs18.5.759
  mac: /Applications/Houdini18.5.759
  win: C:\Program Files\Side Effects Software\Houdini 18.5.759
project_scan_dirs:
  - path
projects:
  - project_temp:
    name: name
    path: path
    default_args: args
    initialized: no
renderers:
  - OCIO:
    env:
    path:
  -redshift:
    env:
    path: