None:
  appdata:
    initialized: true
    open_last: true
    last_opened:
      name: test
      path: /home/skye/dev/Pysoma/testprojects/test
      config: /home/skye/dev/Pysoma/testprojects/test/.config/project_data.yml
  houdini_versions:
  - '20.0':
    - '547':
        linux: /opt/hfs20.0.547
        mac: /Applications/Houdini20.0.547
        win: C:\\Program\ Files\\Side\ Effects\ Software\\Houdini\ 20.0.547
  renderers:
  - name: 3Delight
    ACES: null
    env: null
    path: null
  - name: redshift
    ACES: null
    env:
      HOUDINI_DSO_ERROR: 2
    paths:
      linux: /usr/redshift/bin
      mac: /Applications/redshift/redshift4houdini/
      win: C:\\ProgramData\\Redshift\\bin
  projects:
  - name: test
    path: /home/skye/dev/Pysoma/testprojects/test
    config: /home/skye/dev/Pysoma/testprojects/test/.config/project_data.yml
