None:
  appdata:
    initialized: false
  templates:
    project_template:
      name:
      path:
      default_args:
      initialized: false
    project_config:
      initialized: false
      user:
      init_date:
      current_date:
      last_opened:
      times_opened:
      dates_opened:
      houdini_version:
      config:
      env:
      houdini_install_path:
      project_name:
      project_root:
      paths:
  houdini_paths:
    linux: /opt/hfs18.5.759
    mac: /Applications/Houdini18.5.759
    win: C:\\Program\ Files\\Side\ Effects\ Software\\Houdini\ 18.5.75
  project_scan_dirs:
  - 
  projects:
  renderers:
  - OCIO:
    env:
    path:
  - redshift:
    env:
    path:
