name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-image-tag

      - name: Create release
        uses: actions/github-script@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const createRelease = async () => {
              const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
              const { owner, repo } = github.context.repo;
              const release = await octokit.repos.createRelease({
                owner,
                repo,
                tag_name: 'v1.0',  # Replace with the desired release tag
                name: 'Release 1.0',  # Replace with the desired release name
                body: 'Release notes here'  # Replace with the desired release notes
              });
              console.log(`Created release: ${release.data.html_url}`);
            };

            createRelease();
