name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}

      - name: Convert image name to lowercase
        id: lowercase_image_name
        run: echo "::set-output name=image_name::$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')"

      - name: Build and push the Docker image with lowercase name
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ steps.lowercase_image_name.outputs.image_name }}:${{ github.sha }}
