name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: python:3.11.4

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file /app/Dockerfile --tag pysoma:$(date +%s)
